version: "3.8"

services:
  mysql-test:
    image: mysql:8.4
    container_name: wavedeck-test-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: wavedeck-test
