name: CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  lint-and-test:
    name: lint and test
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.4
        env:
          MYSQL_DATABASE: wavedeck-test
          MYSQL_USER: test
          MYSQL_PASSWORD: 1234
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3307:3306
        options: --health-cmd="mysqladmin ping -h 127.0.0.1 -u root --password=root_password" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: setup redis
        uses: supercharge/redis-github-action@1.1.0
        with:
          redis-version: 7.2

      - name: install dependencies
        run: npm ci

      - name: Wait for Redis to be ready
        run: |
          for i in {1..10}; do
            nc -z redis 6379 && echo "Redis is up" && exit 0
            echo "Waiting for Redis..."
            sleep 3
          done
          echo "Redis did not start in time" && exit 1

      - name: run worker
        run: npm run worker &

      - name: lint
        run: npm run lint

      - name: run test
        run: npm run test
